=== sponomary/projet-documents-structures-TAL/ex2/ex2.dtd
<!-- DTD pour les bibliographies -->
<!ELEMENT bibliographie (livre*, article*)>
<!ELEMENT livre (titre, auteurs, tomes?, edition)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteurs (auteur+)>
<!ELEMENT auteur (nom, prenom)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT tomes (tome*)>
<!ELEMENT tome (pages)>
<!ELEMENT pages (#PCDATA)>
<!ELEMENT edition (editeur, lieu_edition, lieu_impression, isbn)>
<!ELEMENT editeur (#PCDATA)>
<!ELEMENT lieu_edition (#PCDATA)>
<!ELEMENT lieu_impression (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT article (titre, auteurs, publication, avis*)>
<!ELEMENT publication (nom_journal, numero_pages, annee_publication, numero_journal)>
<!ELEMENT nom_journal (#PCDATA)>
<!ELEMENT numero_pages (#PCDATA)>
<!ELEMENT annee_publication (#PCDATA)>
<!ELEMENT numero_journal (#PCDATA)>
<!ELEMENT avis (#PCDATA)>

=== sponomary/projet-documents-structures-TAL/ex2/ex2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE bibliographie SYSTEM "ex2.dtd">
<bibliographie>
    <livre>
        <titre>...</titre>
        <auteurs>
            <auteur>
                <nom>...</nom>
                <prenom>...</prenom>
            </auteur>
        </auteurs>
        <tomes>
            <tome>
                <pages>...</pages>
            </tome>
        </tomes>
        <edition>
            <editeur>...</editeur>
            <lieu_edition>...</lieu_edition>
            <lieu_impression>...</lieu_impression>
            <isbn>...</isbn>
        </edition>
    </livre>
    <article>
        <titre>...</titre> 
        <auteurs>
            <auteur>
                <nom>...</nom>
                <prenom>...</prenom>
            </auteur>
        </auteurs>
        <publication>
            <nom_journal>...</nom_journal>
            <numero_pages>...</numero_pages>
            <annee_publication>...</annee_publication>
            <numero_journal>...</numero_journal>
        </publication>
        <avis>...</avis>
    </article>
</bibliographie>
